<?php
/* @see Mage_Cms_Block_Block
 * @var $this Hatimeria_Info_Block_Catalog_Product_Addinfo
 */
?>
<div class="block">
    <div class="block-title">
        <strong><span><?php echo $this->__('Additional Info') ?></span></strong>
    </div>
    <div>
        <p><?php echo $this->getProduct()->getBlockInfo();?></p>
        <?php echo $this->getPriceHtml($this->getProduct());?>
        <?php $attributes = $this->getProduct()->getAttributes();

                //Zend_Debug::dump($this->getProduct()->getData());
        ?>
    </div>
    <!---->
    <!--        --><?php //foreach($attributes as $attr): ?>
    <!--            <li>-->
    <!--                --><?php //echo $attr->getName() ?>
    <!--            </li>-->
    <!--        --><?php //endforeach ?><!---->
    <a href="<?php echo $this->getAddToCartUrl($this->getProduct()); ?>"> <?php echo $this->__('Add to cart') ?> </a>

    <?php
    //taki sobie poligon - powinno być w Model/Post
    $model = Mage::getModel('catalog/product')->load(23);
    $price = $model->getPrice();

    $post_model = Mage::getModel('hnews/post')->getCollection()->addFieldToFilter('author', 'ala');
    $post_model->load();

    foreach($post_model as $post){
        echo $post->getAuthor();
    }
    $helper = Mage::helper('hnews/data');
    $output = $helper->__('Hello');
    $enable = $helper->isModuleEnabled('Hatimeria_Info');

    $helper_sales = Mage::helper('sales');

    Zend_Debug::dump($helper_sales);
    echo $output;
    echo $enable;

//    Zend_Debug::dump($post_model);
//    Zend_Debug::dump($price);
//    Zend_Debug::dump($model);
    ?>
</div>